### ISSUE TITLE
check_mem_region unavailable in new kernels

### ISSUE THREAD

**Issue by hauptmech** [roboticslab-uc3m/jr3pci-linux#2]
check_mem_region() was depreciated because it gave no guarantees. http://www.makelinux.net/ldd3/chp-9-sect-2

It was removed somewhere in the kernel 3 era.

Removing the line in jr3pci_driver is sufficient.

```diff
@@ -139,7 +139,6 @@ int jr3pci_probe(void) {
      if (!pci_enable_device(pci)) {
            memregion = pci_resource_start(pci, 0);
            size = pci_resource_len(pci,0);
-           if (!check_mem_region(memregion,size))
              if (request_mem_region(memregion,size,"JR3pci")) {
               jr3_base_address=ioremap(memregion,size);
               printk(KERN_INFO "jr3pci: mem mapped succesfully\n");
```

**Comment by jgvictores** [comment]
@hauptmech Totally agreed, fixed via 3cb1a29cf3782b3d3808d3e8f9c2d65a91499879 at current `develop`. Please don't hesitate on putting new issues/PR, I really do not know how I didn't see this before!
