### ISSUE TITLE
linux/uaccess.h needed for kernel version 4.13.0-32-generic

### ISSUE THREAD

**Issue by tdl-ua** [roboticslab-uc3m/jr3pci-linux#3]
Hi,

It seems that when compiling the driver against kernel version 4.13.0-32-generic, the include ``<linux/uaccess.h>`` is necessary. Otherwise, the following errors will occur:

``[...]/jr3pci-linux/jr3pci-ioctl.c: In function ‘jr3Filter’:  
[...]/jr3pci-linux/jr3pci-ioctl.c:54:8: error: implicit declaration of function ‘copy_to_user’ [-Werror=implicit-function-declaration]
  ret = copy_to_user((void *) arg, (int *) axload, sizeof(six_axis_array));``
       
``[...]/jr3pci-linux/jr3pci-ioctl.c: In function ‘jr3SetFullScales’:
[...]/jr3pci-linux/jr3pci-ioctl.c:61:10: error: implicit declaration of function ‘copy_from_user’ [-Werror=implicit-function-declaration]
  int ret=copy_from_user((int*) fs, (void *) arg, sizeof(force_array));``

I have now included the header in ``jr3pci_driver.c`` one line before ``#include <asm/uaccess.h>`` such that it is known in ``jr3pci-ioctl.c``. 
Initially, I added the include in ``jr3pci-ioctl.h`` but user programs such as ``test`` will not compile then due to the following error:

``jr3pci-ioctl.h:3:27: fatal error: linux/uaccess.h: No such file or directory``

I am not an expert in linux kernel module development, am rather just a very grateful user of your driver. Thus, there might be more appropriate ways to solve this. 

My forked version of your repo can be found here: https://github.com/tdl-tbslab/jr3pci-linux

Cheers,
Thomas

**Comment by jgvictores** [comment]
Created PR #4, merged at daef0c23044e4137881024cf1269c47e88ada100

@tdl-tbslab Thanks!

cc: @hauptmech Now closer to https://github.com/hauptmech/jr3pci-linux/commit/437571209b6d1b97b8a1c2e043d0470dbadf272c (only missing `#define` of device). Merged @tdl-tbslab commit as was more specific to issue.
