### ISSUE TITLE
New kernels

### ISSUE THREAD

**Issue by lepalom** [roboticslab-uc3m/jr3pci-linux#7]
Some of you have built this driver in modern kernels (ex: 5.x) ?

**Comment by jgvictores** [comment]
Hi,
Most recent documented was `4.13.0-32-generic` at https://github.com/roboticslab-uc3m/jr3pci-linux/commit/0a5b0155c36994e5ce1947b856021d9195f1b8d4 (related to https://github.com/roboticslab-uc3m/jr3pci-linux/issues/3 and https://github.com/roboticslab-uc3m/jr3pci-linux/pull/4 )

**Comment by PeterBowman** [comment]
Works on 5.4.0-128-generic.
